title: AI for Justice
logo: /assets/img/logo_AIforJustice2.png
description: Workshop on war crimes archiving
date: 11th, 12th of June 2025
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
