title: AI for Justice
logo: /assets/img/logo_AIforJustice3.png
description: Workshop on war crimes archiving
date: 11th, 12th of June 2025
place: University of Oslo, Norway
organisation: Center of Excellence SFF Integreat, The Arctic University of Norway, TruthHounds
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
